export { default as heroimage } from "./heroimage.png";
export { default as company1 } from "./company1.png";
export { default as company2 } from "./company2.png";
export { default as company3 } from "./company3.png";
export { default as company4 } from "./company4.png";
export { default as company5 } from "./company5.png";
export { default as tromhend } from "./tromhend.png";
export { default as image1 } from "./image1.png";
export { default as image2 } from "./image2.png";
export { default as image3 } from "./image3.png";
export { default as image4 } from "./image4.png";
export { default as research1 } from "./research1.png";
export { default as research2 } from "./research2.png";
export { default as research3 } from "./research3.png";
export { default as research4 } from "./research4.png";
export { default as section } from "./Section.png";
export { default as pro1 } from "./pro1.png";
export { default as pro2 } from "./pro2.png";
export { default as pro3 } from "./pro3.png";
export { default as pr1 } from "./pr1.png";
export { default as pr2 } from "./pr2.png";
export { default as engineer1 } from "./team1.png";
export { default as engineer2 } from "./team2.png";
export { default as engineer3 } from "./team3.png";
export { default as blackcard } from "./blackbg.png";
export { default as engineer1s } from "./team1shad.png";
export { default as engineer2s } from "./team2shad.png";
export { default as engineer3s } from "./team3shad.png";
export { default as card1 } from "./card1.png";
export { default as card2 } from "./card2.png";
export { default as sidecard } from "./sidecard.png";
export { default as renovation } from "./renovationbg.png";
export { default as footer1 } from "./footer1.png";
export { default as footer2 } from "./footer2.png";
export { default as footer3 } from "./footer3.png";
export { default as footer4 } from "./footer4.png";
export { default as footer5 } from "./footer5.png";
export { default as footer6 } from "./footer6.png";
export { default as footer7 } from "./footer7.png";
export { default as bluecardbg } from "./bluecardbg.png";
export {default as blue1} from "./blue1.png";
export {default as blue2} from "./blue2.png";
export {default as fc1} from "./fc1.png";
export {default as link} from "./link.png";
export {default as herobg} from "./herobg.png";
export {default as aboutcompany} from "./aboutcompany.png";